---
hostname: site-b-m710q2
hardware_profile: lenovo-m710q
netmode: static
nic: enp1s0
ip: 203.0.113.21
cidr: 29
gw: 203.0.113.17
dns:
  - 9.9.9.9
  - 1.1.1.1
# Secrets (password_hash, ssh_authorized_keys, etc.) sont gérés via
# `secrets.sops.yaml` adjacent chiffré avec SOPS.
