ssh_authorized_keys:
    - ENC[AES256_GCM,data:ZqvKFSIsevJq0glwJfq+PGdhRgqR2RWMMPloBF7N2NZHg8N+/OVht346Awb3NofDiHHEmKADBZeKf//fhOyqQNfFpk1fUSH+yL8F,iv:jiCqLRP5aEPqQxt6NY5ZlN+gJWX2VisMAHOKQaqqO18=,tag:PCvddMXOqomKuWaOYcpWeQ==,type:str]
password_hash: ENC[AES256_GCM,data:xbybBRJIjceOjpblilCSpp4CMLRKRI3DzxHqLAQoBA2yYu78oX4riKp7BrByZbyeWtee2L48GISvcnPpObOJdrbg7ZqOLm57SStgwZ2KGHNqxg3l+IKRPDOKA3YxYJgYFCaGCDyu8eW62w==,iv:aP7ctRfJgcMAN18hmZOoH1919d9gfqDWJM7N7ngCKoI=,tag:RKUxgCh7mP6Nowfmmsuseg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFlTV0hVMjZsdEpucEVD
            R0htNDRkVTMyMU1DUm5DZm83dUNnK1krWkdzCldLVkQ5eFU4dmN5NVY5a05sZ0Rp
            RktVSVhURURVUXc4QXRENnc4Q2ZETjgKLS0tIDdDS2p5SmJZb1h5RlhHSkZTT1By
            RFFiM1lEaHRJYmZwdE1yb2I2TzEyZTQKAZ1ZVrfja241lwWUPVkT7d97jQBFp/Lb
            iiZ2zwG8Hs66ZcKM/dJXEGENb8NyVCnnmLQAWtk+VDuK/BHiEgovQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:17Z"
    mac: ENC[AES256_GCM,data:EY6Kg5SnGnb1gyr0NJCmL/okzwRy6sX23GJtHpxOARMSGS5P/J406OJy6pN+Pu7oZjUbzRHvBC6R5CdPi7qvblD53RFpBdR1DmkwAkDbuxTiBAN4/Mmkb/x/v9oB69zbMU+cIRNwjPY4viS/XKmkFFuVBQW/6VgrUzlXTY8MdYo=,iv:D6v0joJnhZiSBiruum2jUc2qDFLFBE2E4B6eei+VNZc=,tag:ECz6X8zf8QwijHUuSxBlog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
