---
ssh_authorized_keys:
    - ENC[AES256_GCM,data:CVfx9E+ckiqCZ2lZqSqLPspj9WdwPsB8KlKdwWnzuzl4kvShOOfxOqwf0g==,iv:0ld5nQmMdpcovUsBdi6wIxfB9FaKlAULWwsL3AY7yzQ=,tag:jzGRt0RsusNS7ECc5J1mfQ==,type:str]
password_hash: ENC[AES256_GCM,data:SJG919wxnYqo7Vla27Kf0tx0xVwOAw==,iv:u4nVuMS8EsvmceHPn5usJ1odRUHkZGNrVdtrfQSQHUg=,tag:YCNmpjcGnfSjq89wOud6+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1me73alnny85u4u0ck6m7y3c4awpeuxpwfekak50w343da2dguvcq5z8cm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETmljekh5UElraGZFampn
            OEczVlJINTRna3hBUzRxakRUTGtSUjlpT1ZNCmFoRGpjcmhEQm5MNDdwV3N0S05T
            aEx1VmJpV2hjeGZ3VUNlZ3hBUzBhaWcKLS0tIHVLMFh5Z1pkSG5LbVU4Q1hHT25D
            VnkvQ2w3ZCtzRnB2V1Zqa2dIK2JLekEK7JJOsd/Q1lAIE++UbHA6Gw83OXXoD9y9
            WRUbb7XCg3AkHeHhZAQxhCtIhwxlU7IABZZYJhEc6Tr/AwC68w/AZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:36:58Z"
    mac: ENC[AES256_GCM,data:vKCOyeIe8Ori57xS4ZFrMQCZXwKrWn4/9TmqWIrsDvU9v1gCw4pryL6+ic50l/w+z+HpNAw7q62WaRt8xqfWXj61jYINfcozW5UQaDJ/+3ZfOIpDe3O+nUHKErIQTWPXzbaWwLjoOyqRnzBG8I7FPwgJ3vT2F/HytZpKTw8q7Hc=,iv:5QqjwvwGsP9JvA9CQ9DyiTNRKdnbsi8kMHLph3SDM9k=,tag:yrk7sRU+XRwxGUe4YGI6qA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
