apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-values
  namespace: metallb-system
data:
  values.yaml: |
    controller:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    speaker:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    crds:
      enabled: true
    configInline:
      address-pools:
        - name: public-services
          protocol: layer2
          addresses:
            - 203.0.113.10-203.0.113.30
      l2Advertisements:
        - ipAddressPools:
            - public-services
          interfaces:
            - eth0
