apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/flux-system
patches:
  - target:
      kind: ConfigMap
      name: cilium-values
      namespace: kube-system
    path: ../networking/cilium-values-patch.yaml
  - target:
      kind: HelmRelease
      name: cilium
      namespace: kube-system
    path: ../networking/cilium-helmrelease-patch.yaml
  - target:
      kind: ConfigMap
      name: metallb-values
      namespace: metallb-system
    path: ../networking/metallb-values-patch.yaml
