ssh_authorized_keys:
    - ENC[AES256_GCM,data:pqPmxjIsi05mx6LZsjXY+WulTw+uaSJ47D3DL6OvcB4N6m4H/4jOvVdFK0m54+SQUyaY3lNda906BaLgM83QcuQetYyhFJvkFRZ8,iv:ltAtjgKy1UYLjREf6nMBkS7XxX44n+xLMRiWdzu9Oa8=,tag:TIJjB65WcuszseuU0N4e0A==,type:str]
password_hash: ENC[AES256_GCM,data:IA0s4tyYCJmuecZQ+sejDYGwkIu2t32Ssx3XZVPZ4BeDqi17hTkCjqsD8DmLSk/pX/yUcEMBUvdGPK3y50zoryUPms9h/koofZnWbiPnuC3guW2Bg53onekLYD2I5caeXt/O+Jizej/AKA==,iv:lZdFvXQNzQQhwE5V02IlFZ0TADNAj+ZcsXAAwLNhDqM=,tag:vVQvs+MgV4JkctcdMO5A7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZjNlSkNqWmhadUJNWk0v
            VGN6YXRZd0orUE1WblBtR1didDRwYzR3ZzJ3CmZWMk5wY2FVU1ZON2s3azlHT01Y
            WEhaTmlBc0FUWkpuT3JuQTMrdWtlRmcKLS0tIGhHQUl3VEw2SlBrc3lnNUx3ekdM
            WXd1MDlnZG13eGxjTEtXenVlcHNrTDQKCw6ZkoQEsZOOG3UheKsy1LzniK3r4Axo
            YqplcQ/XoFxxycfQTuy69Ax+AHyqRAz0VE4JXFknne4Qw0+jXBw3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:17Z"
    mac: ENC[AES256_GCM,data:SSNGlfCH89lgNT/GS6CZgCg+JG5iG6rDSuDut96pYXqqasMXagJuT5FZmgM+yyxaVQrhMyyq0FKlApphdFwiCdPwOSgR/e2jj4113jjYbOybvu5l5Y9tMf16T0377pGgnEirfwjmeCqUW2wD1yNvBmo/529L7I3/+Of84Vr7apc=,iv:t3eqltaMOotlLaGziDjqYqBKSJ+2cQF9Bj/rLrcP8xo=,tag:To6hxLBc1ROm4jZGR8jBAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
