---
ssh_authorized_keys:
    - ENC[AES256_GCM,data:cL8jQkjc54UVEo6wCGzWXJ315AYMXx7Ca6NobvOts7lP+quh8hka50lcRw==,iv:a24ncWMOxXFp0QKKzwHRvADK49mVroG/CNeUcl2ChqE=,tag:UnrNfUpmFkigPdvCS3loeA==,type:str]
password_hash: ENC[AES256_GCM,data:bKgeHLvJv8j9IiSJ5lMgBbD4MwoptQ==,iv:VvjJBHtCynMpAft8yGMsgQutGVm5Dbv+UQCOuKfg2Ug=,tag:QG8FB8mnycG3RSFKz1Q9Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1me73alnny85u4u0ck6m7y3c4awpeuxpwfekak50w343da2dguvcq5z8cm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NlIvSmEzUGk0SHN4RjU1
            Tml2WVBSQ1E1YzZINkpOSEJFbTF5QUljVmtrCmx0ZC85TUNnYnU5eGxzQ0x4aGZo
            NmJub3JIc1BDd2lxYkxhQjdvK3JPa2sKLS0tIG1jdEhCcW9TMEdzWTVSNHY5UXdi
            bzNhWlVjbXNCKytpc3lkOHR1ZGhkdUEKyH9eMLmnHRg2xfiQgnhs0/NZNbD0zXay
            K0derejWT0q3FUqQrRRNJYGYZ+/4yfVaXb9YjCUAW/ehGhmOHa5Q0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:36:58Z"
    mac: ENC[AES256_GCM,data:DTD8KBa7HLRidKZXgCFPkryt/iVLz00QyFuVYwL+wSpROj3rBQz+TOObyjXHi/y3rqO5y9dJsiIkQMmrbeRGf835iXqJ33D7KmKY20OuldDj7cyZKbEan2IrzFzFEijAiSvmxtQZpA+Xx8KYqg2reUdcLIhVjpvuq9OImZ+6gak=,iv:9PER0hKq5ta/MsbC5ycDHv4D5lyDgnoUF4Ag+xQGfm8=,tag:tWwJshv6GRfks1xdBl/mFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
