all:
  children:
    site_a:
      children:
        site_a_control_plane:
          hosts:
            site-a-control-1:
              ansible_host: 10.10.0.10
        site_a_workers:
          hosts:
            site-a-worker-1:
              ansible_host: 10.10.0.11
            site-a-worker-2:
              ansible_host: 10.10.0.12
    site_b:
      children:
        site_b_control_plane:
          hosts:
            site-b-control-1:
              ansible_host: 10.20.0.10
        site_b_workers:
          hosts:
            site-b-worker-1:
              ansible_host: 10.20.0.11
            site-b-worker-2:
              ansible_host: 10.20.0.12
  vars:
    ansible_user: ubuntu
    ansible_become: true
