encrypt_disk_passphrase: ENC[AES256_GCM,data:oqvmjCNIghe9+qvWxCFRv0sWM9AklpOjSw==,iv:C1YZf1GbFGW2qphd9+VjvxGW3kU6pDGz4fwTS/qdZ8A=,tag:4Jhh0pfgfBW4PNBw9QheTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12j8qqj94jtn7xhg0qc2zwftsfpn7xre4ztfuyk607ha9zqwy4qusyysk09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UHRDVnNYOUVteFFxSkhk
            Y095VTgzay8vYVNLQmxpZThkZUFJbXFGOWc0CmhiS2ZWZldhbytMNldKK21FR0x3
            TjBicW1xQzJhcVJ1ZDQrU1NsNFFvRHcKLS0tIG1oMFBIYW14MGZaWnc1ZWt1Mmg3
            ZjBYWlByaWoyTGYvWFB4dlBQQnhjL3cK/yoMufMkgUWiSSuLu4ItnbJrVShhXzyf
            zKl2UxtMHguOinTdSTA2IRug7F8zS+OLZHqDi7Qi6Blko2w8opl7NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T22:13:37Z"
    mac: ENC[AES256_GCM,data:TGQnEcf7JEAcCs5FGTcBVol1Q+UWy7htAQxtmU3hjGbrpberwL+ryh63c6xnwt8yyboOC66bkkpqt28+nhU858kMlyko7tGBM89wvfxDzYdx1CUCljyhbAoM/Dw7W2tPnILFvRqHuzgPDK5DJfH3X6kSVorQjIxj765s/USHEXo=,iv:fGCWK4knn22X5AlD4/MpvrogYgsTJF9SJ1QKwWYg2Zo=,tag:GB09RMdrx23s7WoCSClQ+g==,type:str]
    pgp: []
    encrypted_regex: ^(password_hash|ssh_authorized_keys|.*_secret|.*_passphrase)$
    version: 3.8.1
