---
ssh_authorized_keys:
    - ENC[AES256_GCM,data:IDqxzEiUPEwLu6x5I/uqmtGxTn+EWxTyjs5UaTE7jTDCPLiIazi8zjcvXA==,iv:Xewqet3otrjp1IaoKeN6GW6J7LKF/gvQIwlzvJUte0Q=,tag:nIKGHLPWYqb6wE4umXz9Wg==,type:str]
password_hash: ENC[AES256_GCM,data:vW3wy271JpBQQe+A8msAi6kVEGnBkQ==,iv:lkaTR6QqyzYh0dA6G4vFGLIzfcZgPblfzIZoRHIAXwc=,tag:2n7Fi2Yj+CD9j8107eFTOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1me73alnny85u4u0ck6m7y3c4awpeuxpwfekak50w343da2dguvcq5z8cm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcEc0UlN2SFJXTEJFT1ZE
            Sm5sZnlqSEdiYlU5bDRrYzJrUFFMS0YzbUV3CmtDMGpZMGZpaTZrZ3crU1NHRDhl
            NDByamh4Qy9FZmN3Mjc0U3NyU05pM2MKLS0tIEdXa0J0UURuL1V4VlNFVXhNQ0lm
            TGdjTmZLT2lQYnVtWnRJSlcyYy9GV3MKH+ld/tMCGRYtIawFjMnt1rgMo5vxvZro
            FlKKH/WEj9FxqrMz4aG8R+j3zid7I6Yqq/IH4i4t6sbqsEY4J/s/dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:36:58Z"
    mac: ENC[AES256_GCM,data:mEpsOo7sX7+jDoqeM1ZOo84TXryj4iLTdRjANRj+ec+tsvGUW2LzcMctUETauebA4MlFPEAvywe2P8zWDVT0Qm8sAG61lsaDyIJlL0LLpO7u6OLVy5Q/6F8oKEsnP+IY+0ZWzXaZZuhIg8ZE88zLQcEN0SvE8GQS2vKATtxdvic=,iv:zX9DJdoKdWFD4Jttc4O/v9PHyQIJTqLLgkMPvTtCub0=,tag:oj0pqHB6vSacNBR/RVZKLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
