ssh_authorized_keys:
    - ENC[AES256_GCM,data:h6JSrFqpwRFrgP/Quuys371dx1XOwEmvmKcmT+t3TXMcsWtCaRTk79/JxV51UWRWfH+ju4nLZfpOiV/Fg6BHo2RmE//nU+ibLLky,iv:Mcf4CCNLSTP8YkQ9njnqoBG2fdhFfiIRSuJ2BZi5xII=,tag:QEWybanVXye23v0IUr4RPA==,type:str]
password_hash: ENC[AES256_GCM,data:e0Ke0AcjAKo8olJZ9ZDbQ/rhkT7atRBhHmWfHkJbDPbWcf1BTMhrXo5Cm4SWyCWaSKwTCxeoxNE2V3w3VBcOaP1i4cwB9QOWt2zLk0Pr3IDzmjIM2tu7rjuGumHaSMCetYwi6ymxHowA8w==,iv:dNJ7OO0ozo+VdnjPTDRMruZWnuFeA98i4B3+NGZ/10U=,tag:kwtFRbDjgPRIxjTfa16dyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ3puaG1lYm5MSllKcnVz
            Vk42cUJEREdDdFZ4ZksyOU1XS3ExNnNvaEVJCmFLTzZDbDRNYytXRmU5R0hPeWZF
            a0F0ZGFvdnlIRjl5UGxYZVhYaGxDVUkKLS0tIE44QlBpYmVrTXhZYXUrYm1pdUth
            NXk4Wk1VNVhXdFlyeTZHSUNkc1h1MFUKJ9JLtWCK0GyIB7RipgnNfXdlsZoNr7Wd
            m2k64bFi9srUg1rk9nyzF/sjJm/IS2Ji2rEbVfT3AXsPJEcAiCsP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:17Z"
    mac: ENC[AES256_GCM,data:yInQBW23jor6U8r3e7X/GabCKtZWaqABata/iond7EElu16rxOiOkYRvFYRIhdBIsE71ydKSGKHwk7AB2lVAXHP6LQ6X3+Tw97JDuLOHvsnYer6mDFIFPPdZ3kDQndnE4tjR7OunwmlRVjMSWSE0c7rp6VaOKEfKcfjXTkC+f3w=,iv:KDWV/2ZsYMMhle4pJ5DgXOLH1RnwgXGNbYuoKQEMyeM=,tag:RqdUswnjxjUOSjs6mYWuVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
