---
ssh_authorized_keys:
    - ENC[AES256_GCM,data:ApzI3Lkpvgdh9twiTd04Fcc99vqgd7cn8vO0nHfMTA27VJhgKGOrKng1dw==,iv:qXruZ0dcxqYqkYOHyffs+3ItTqrQRXBc0JaC1i3BnW8=,tag:cjvWK8jVokRH9bJFKfo+Bw==,type:str]
password_hash: ENC[AES256_GCM,data:JQkF1P2Ev+05/KSaq52l1uUBORPBAQ==,iv:OkHEBuwScbRnX+ukusWloThZD9KcDdIej2cMfFVVvsM=,tag:hv26IeS+H13iTLom+K0VWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1me73alnny85u4u0ck6m7y3c4awpeuxpwfekak50w343da2dguvcq5z8cm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNekcyN29hVFZrTVlVRzR4
            OTJSeHp2Q09lVEVkZjlCTk1NbHNvTVpaR0I4CjZDRzlHNFdUbVRLYmJTM0ZDczUz
            RzE1OGMramdwckNmT0NzdVFoZ29DeU0KLS0tIFowYktocDVmVkJnKzUrK2FCL250
            ejFwd1Z4M1VSS3pJMVpoNmpzUzJjbFUKUzluCqg5Y3gTpHo/EWvV7DKb5QNdvyKu
            +xKaQkdPcCPfBZ7VFEGq8/rF47zHoEowrLcnAsyTrbuqdI8Iw0GSEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:36:52Z"
    mac: ENC[AES256_GCM,data:hQb0ttHS4ZFXfsJTJVVPND4lR+uv/Vu1nAwT01bpj2NVf02u0P0rMyuWQHIi8My4QBVJCs0C6hVatRnTH3Z14jLQFreQYcY2ZigTfqpHxFon417RR6BBvqHa7N1gmCtGk5tRNAopx1a8wueB4aqA9ZIAT7aFHBxIrk2mDPuArZ8=,iv:xdh9Q8MPXnOI1P6v33eK8Dt2NIn1ToUnWKFLvSyHDFc=,tag:5XfJGv9MSxcA4TcYL0NfGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
