ssh_authorized_keys:
    - ENC[AES256_GCM,data:NTQexGuGtAWaka4NOY3YQgqvYMdNmlwqiJvwQYwBGXc1/FvtCXvtxNgtolcNVRm5t7ciq9ngtFyhPa5lVvdX++gTbFTQObm2FPIm,iv:Aslv20QLT0XnwLu18LcSLH1eipwsyfAFdibrGi6kS6Y=,tag:kDbn2Nb/BKxvDnM+cOW4tA==,type:str]
password_hash: ENC[AES256_GCM,data:Mabgi7XhPuF2pbAUg/XDEC0cXr/nfqvQmErMVmH2daEVccWHvoo73/EQz7/LxDEVQMv+sP6a/hTaaGQX/iI5dC+mzMpJ1lLFTs0XODnCnrHqya9S0T/FAXoP05np5oKMhVhDQfw+ihJ6Kw==,iv:36KZggi5oRHa8O8WoZfWtN5ngW3ff463UlUdKKeQwJ0=,tag:fQceps+DwPYkn0PEVkwEMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTzU1V3ZnVjUvYThvQU9l
            N3AxTzZSOTFJeUtuNURmMHROVHFFK2xkY3c0CjRnZWF6dnprMlRsMFVWRSt0cnBO
            dFJPSldGU2JWa2FhQnNYZ3VhZnhYUEkKLS0tIGdsM24yNWg2c0ZrbksxTXpmVVhP
            Q3hTaWJKaVFzdkFDdS8xNU1sa1FYTUEKG7rtcy/ta7RYnlTkvCIIJtTfBhi3g26a
            MHiIpjv0omZMtURppcsgzM9FCnr2iOlC+CCQs2zEy5ogZOcUf4aN5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:17Z"
    mac: ENC[AES256_GCM,data:OmrJxKNxdSkvljBfnjNl1Z2fy41rSIqk8FEoaf2plxfmu/2sokFa9oz3JInXmBu60sVcwJZWhoS4W9Itk5ZRdWg4H3DG2/AMoImlCIqJ6egUsaG1pOCUlrE9EZoYkIrv4RBz3evKpr/2+3K+DoQMwYP6VYOKQ2MRjnTnCktndq8=,iv:lQrx9dWjuFHUwn1pmQE+Z+PqwywUIufH31q6+pUoIEw=,tag:iSh0PjnEfyLX8dh5Z4qVmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
