ssh_authorized_keys:
    - ENC[AES256_GCM,data:JVMLA2lk/QYY6e3Q0b++J3WMblXC5k+G8l21JdeEIqKkAqiSHXZFMiu/LrvwvpCkOBiR5Prdldze7XHwlZ0mLxxkZrrbhmf2ZcuQ,iv:FVeJkHP16NbFbosujBSa+JNWWBnmGqV4vPV3eHY5mZM=,tag:9gdSQugF6SmZdpNFIMVSyg==,type:str]
password_hash: ENC[AES256_GCM,data:X1uTbHCGp79z7wTGSbVfx3S/GHl0LZcpF5JkBZfupH++SAtNJLGpL2mgwtX10FtUyNdd4NVGJ/vXSnsQiX0y+uNX5Rn2iL38cXUIdy5iVAnIzZzn4u1X5ahUwxihfWHAr3MQg27lUDYZbg==,iv:tLmSLoqoxdbRH645LT7nz+XOtFiTbXCyNnRf7AbG4hE=,tag:IpOUvn/ew+LmIRuePty8vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMDEvSTZNYmVuaFZYWWFF
            ZW9qc3F1RDJieHFmUTh0em1NalMybnc4UVZvClpHWExPVFh3aDVadzZJVHB4NzBI
            cjNTSXZOb0dxOUhqTzdOamRHdkpVK1kKLS0tIGg4U1ZBc0hrM1lwMTNYcXdFanNu
            Sk15eVdWVlJXVEZoYnliZjlwOGNJMmcKQQET327E7skBWuIhUxqFqwyXOPpv+7oa
            A1IfZrfk2olhhemh/0O238KWoV3VrhpBqO6UcwrwfeK54ZaWNcP4AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:49Z"
    mac: ENC[AES256_GCM,data:Yth0EadwdEMbnJm7Fx4nV4wtZT/iIMVfY4zgFw9fBi046RW7ZeoTGVSlp2G90jv48X/ejXdJ7Md2/VcB9Cs7Q171QGmuOqZP+jo8pPxjMx6FtCNR2EhW6dgBOrV83N27mhpFSdrHKyEMOLpMunkx0xtu51RLC44sb9hhm8zKqjE=,iv:VPYC8pX0D9gB4VCY4B+NExYEXymOq5e4BcrinqUgXBI=,tag:Y1zJS1qJ57S5TeYGGB7Gpg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
