ssh_authorized_keys:
    - ENC[AES256_GCM,data:Chh2108ivhk5IiIEPhacNVqSblO6y6Aj07sr65tSOHXONjbflWJZPLFBUSIjxBGdqEAvpCdy//MtEc9Qbeqaam2onjju+EKmoie/,iv:wKzAZ3T67T68NRyXu1etFTrmxJkr6w4nZybL4/6lnjc=,tag:308sDzRvAYgGEgC8g1rO+w==,type:str]
password_hash: ENC[AES256_GCM,data:39MvaoSyOrzP7RlZqvuLE3Shk1ssqMQh/y4lM3b66iBCoc9XF4Bs1PSMHvOWS+1eeIvj4SQYJ54CLPT7IBFxyUFWpLT7Hblrm13ob4havF4PZ+VDWhtuEdfVoZ9/ay9QnWBuakd+/I4NNw==,iv:ia+Ao0z5XrhsqfUR1avepnTX2SGbaJkIOLz3fQmfF1g=,tag:JFUh0XvTPPa/cTGTi1lhNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOFJ4Rms4RGkzblBuWWlu
            cmx0NllYUFcvbU1pS005TlZzeWZvSzNhRmx3CnpPR0s2VFJXb2JnY0l0eXBEUjQr
            bitnUHBOWG1FNTloZnZmcDI4b2tUVDgKLS0tIFZKUTR0QlRsTExCZlRFWVhnM3h4
            ZnVZZi82bXNORTM0R2k4SmtGdDdUUTQKqza3UkSJ9xpB42A30HDGYtCPdL2jy7j3
            F28Axn/qF39Li5XhjKYgtpRLK/F9TrZIkxZ+1slsyl9mKt3wDpvZMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:17Z"
    mac: ENC[AES256_GCM,data:XEUS2SZjT7h55Wr8mOHk73p/mHekiFBpRxyLj0jR4O7XF1Uly1loi3nQCvl53zQjsP1xt4fPWA934GGWQRawsWdcy18M5R0zir6XcPh43QJc1RycZxndXgTcf/L3SRVepXhnM6beE6L2/q1ijv2LTPFZMn7V7cdEPtMsbVY8CrE=,iv:sJQM6n22j0vS7TARwEhNQNM90OjMT2Zk7/lhdIum0UA=,tag:TyvzwLiSjZBL2SVo0sXMbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
