---
ssh_authorized_keys:
    - ENC[AES256_GCM,data:CDOR5r0Un8P5GCtlYfpb5SMrs6ig3jFbC8NM4E+ZThJmw9B3qH16uuwam5XASCg=,iv:dP4xEx5gE/wF0q5N11vh9yJ+KIyD7NlesthBQ3JhwTI=,tag:a3M42+cN7Eg8PC5qIPmbFg==,type:str]
password_hash: ENC[AES256_GCM,data:UiHxTzZ9hRmDOXqeGjjoSSWEk3vHgQ==,iv:6Lxs8FD2ROMIzfdz0FoeOuu+8RsP3ZwhfZIFHLrXmUc=,tag:Ulii99fdm1LtLZ6vZtPUWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1me73alnny85u4u0ck6m7y3c4awpeuxpwfekak50w343da2dguvcq5z8cm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRTFGMnIwK2VUNVJNRUFZ
            ZU5XRVJBNjNXeDFUU24xMEh4K0ttNklzcjFRCmZQVHlWTnJrK0w1OXVuUTcrYTEz
            MUtNM3c3ZGxncFZYaDh6TjB4b0prWUkKLS0tIGdLcEY4MGpFOTIvZSszYTJNQ1NG
            UXF1T2FRblhJays3Y1hEODMvemRjUjgK9F+NDF7QMzIL7N1gjksliFqJYo5Cf/yw
            d2W038inHFRjLlRGgkPfi3Cinu69SKrPKnIBpmY9lyZH71fYDfm4bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:37:01Z"
    mac: ENC[AES256_GCM,data:BmzLI8zYhnpDpXMpTvlfodqk1mTClEtx+mUVp93TNvOuv+f5x8xbSUOH3Loi7UDUIswYEtJ0+QNcHGV3RI2ZgihbXOQRGzg/pM3lidMZjIpVej6J/ry3bkkObdi0B66Y3hlzjjGfCDAlHWysRrBSvpEy993ZM1C8lO9ZiJJ/cy4=,iv:Uy1B8eLe4G0y4+q270pqfOKJ8yNdAqeqH73u3+zbVfQ=,tag:lsK1NgTi/CuZKKEbh7KYWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
