---
hostname: site-b-dell3020m
hardware_profile: dell-optiplex-3020m
disk_device: /dev/sda
netmode: static
nic: enp2s0
ip: 203.0.113.22
cidr: 29
gw: 203.0.113.17
dns:
  - 9.9.9.9
  - 1.1.1.1
# Secrets (password_hash, ssh_authorized_keys, etc.) sont gérés via
# `secrets.sops.yaml` adjacent chiffré avec SOPS.
