---
ssh_authorized_keys:
    - ENC[AES256_GCM,data:aLqmYdNnAKELlBegZUBap2HkmYdR2fmp8xnzPzCHajmlbmMeF4T1TwDsmQ==,iv:rjCyvfYhgEw2me6UXa/hAFNohjqzoTeFM8+r6lD/2fI=,tag:Hft8w0T4Jl6fAoKRSGa+Lg==,type:str]
password_hash: ENC[AES256_GCM,data:1Til2QwPSiDUXWJcv3KKT4VGq5Djxg==,iv:hPzva7dprXuObfJb/3zA84xh6KvXU4NDXVKZ2jgyb7Y=,tag:QDKe2+LjLnxGE/MKMtfqiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1me73alnny85u4u0ck6m7y3c4awpeuxpwfekak50w343da2dguvcq5z8cm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Tit5Q1FmaWJTTER0Wkw2
            QWtsZUFQNFREOHNRMGZ5eHNsdGhPZUphSEZrCjRFWmdQRjFYMm1Xa1dnWFExVmJj
            SmsvNVZUOG42eUc0VjkvR2E2dEVZd1kKLS0tICtUWnkvdGhqOW4xRUJRa1R2WFpt
            REFSUmdUTVNPYWR3cHNxNGlIMkx5OHMK+57IdMlnnERL9W1tS0BEY1FZNdwiU5Jm
            kwqCKuR9iU8oWysF5r5fyk3U8Ko1bxkiPfEW9SZe2lpZOkTXlcMGKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:36:58Z"
    mac: ENC[AES256_GCM,data:SV9x45ASUWz30uRqdZcWdIriXS6kOx8OgDga74gYC2Xw+kuBXqxvLg3zuoFJLHSKJTztCoGIiqEvbFOG7pcqUUUHZUAh2qpz5VK86lscO9PQgtvpPEkoMI+bf64j711I4freykJaNtHpxgOiBFKdhsGxS197/vlmmANMfVkLh7U=,iv:wpjLNbKkv44ofMTWT+scX5omrnkd79kSFiEGQxrjxFU=,tag:iHIG9AT/DvcYYbYLlhD9Tg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
