ssh_authorized_keys:
    - ENC[AES256_GCM,data:bWUvbb/e+fhLMqVcIrTWdKI5WvcrSNQ9Y5wNopVjRT9gDl/jLmeFiAs+0TAxQS2RnhQnlaYbWcK7qRoYQnQWWnDEYMSz4vvwkZMj,iv:rMu9vLPcdgRMlzutk3Z/xKapz89ylqrC7qRfObU+rds=,tag:V/xIbvRPA15ysTwXGV/RUw==,type:str]
password_hash: ENC[AES256_GCM,data:VyeD6SYjctfIGp9CYRi4AL4aDtBigTa7VfYFe7AvOSMwZl2+RppyumBIUh9IWGOUl0rAUJ2o0PHshDHRn+MsIt4Vl+6a96hVRkiiGuhF63ZRsG9BxyluLLm1QZqXt8wvSQcwSqoVtiMxsA==,iv:ijZXxw4flmzMNzvvSnOyv7WrWh6t3nKj4mAitnYgTlw=,tag:Ekk26LiZX/16tUs8yiVH9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBselNTbmE5amFKMlBISEUz
            WHRaVHdsdEZrNW5GNWwrSnV2cUlYV1JFV1RZCk1KN2JIZU1TUFBzMXpZeHMvUHlF
            eHhkbnROTjdUZ0kybnN6T1BVUmE3STgKLS0tIFZrK0RmTUN6K1d3dXpjZFdDMVI2
            ZlArTnBFWUc1eEhTL1Nud2REWmNORUUKFcig5Qf/0cxnSA0+0LQuWuL+X16rHnBh
            O53HEoUehsE0LOGlveZhAvb+qoMyBSo57W2leGAmwSzOglZp8Zqkhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T14:18:17Z"
    mac: ENC[AES256_GCM,data:vCW+YELYDtzdV7TdlCsfvhMFDjm5SRPvQPdG8pLPH/TKgrQZji5bm7U+uxvwgUu1ThhebI6fEQC1mfqM6BUXOONYpnXxz//ueXVuc9y2AXWji9kQo3szyVNU29jNATMSgh1zm7epxk1Q3LgMCiwJVRz5EMMiTIY2aIWGukb23po=,iv:XTwntmW5PVfrAXwx4kERQfeKyqGPaRKNqYMmFWd0/Kg=,tag:ziR7uyJrsD7xVfCUj5kRMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
